#!/bin/sh
# Set up bugzilla and run apache2
DEFAULT_WEBSERVER_GROUP=www-data
DEFAULT_MYSQL_HOST=mysql-host
DEFAULT_MYSQL_PORT=3306
DEFAULT_MYSQL_DB=bugzilla
DEFAULT_MYSQL_USER=bugzilla
DEFAULT_MYSQL_PWD=1234
cd /var/www/html

# Substitute values into bugzilla localconfig
sed --in-place -f - localconfig <<SED
s/webservergroup *= *'[a-zA-Z0-9.]\+'/webservergroup = '${WEBSERVER_GROUP:-$DEFAULT_WEBSERVER_GROUP}'/
s/db_host *= *'[a-zA-Z0-9.]\+'/db_host = '${MYSQL_HOST:-$DEFAULT_MYSQL_HOST}'/
s/db_port *= *[0-9.]\+/db_port = ${MYSQL_PORT:-$DEFAULT_MYSQL_PORT}/
s/db_name *= *'[a-zA-Z0-9.]\+'/db_name = '${MYSQL_DB:-$DEFAULT_MYSQL_DB}'/
s/db_user *= *'[a-zA-Z0-9.]\+'/db_user = '${MYSQL_USER:-$DEFAULT_MYSQL_USER}'/
s/^\$db_pass\s*=\s*.*$/\$db_pass = '${MYSQL_PWD:-$DEFAULT_MYSQL_PWD}';/
SED

export URLBASE=${URLBASE:-}
export MAINTAINER=${MAINTAINER:-}
export MAILFROM=${MAILFROM:-}
export SMTP_PASSWORD=${SMTP_PASSWORD:-}
export SMTP_USERNAME=${SMTP_USERNAME:-}
export SMTP_SSL=${SMTP_SSL:-1}
export SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com:465}
export MAIL_DELIVERY_METHOD="${MAIL_DELIVERY_METHOD:-SMTP}"

perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' data/params

# Verify bugzilla setup
sleep 5 && ./checksetup.pl checksetup_answers.txt

# Change ownership
chown -R www-data:www-data .

# Remove stall pid file
rm -f /var/run/apache2/apache2.pid

#activate apache2 rewrite module
a2enmod rewrite

# Start apache2
. /etc/apache2/envvars
/usr/sbin/apache2 -D FOREGROUND
